package com.example.omazonproject;

import javafx.animation.FadeTransition;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Bounds;
import javafx.geometry.Insets;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.util.Duration;
import org.controlsfx.control.Rating;

import javax.mail.MessagingException;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * This class acts as a controller for the product-page.fxml
 *
 * @author YuXuan
 */
public class AutoFillProductPageClass {

    /**
     * DecimalFormat is used to format numbers using a formatting pattern.
     * It is used to display decimal numbers in 2 decimal places
     */
    DecimalFormat df = new DecimalFormat("0.00");
    /**
     * Stage is used to represent a window in a JavaFX desktop application
     */
    private Stage stage;
    /**
     * Scene is the container for all content in a scene graph
     */
    private Scene scene;
    /**
     * Root provides a solution to the issue of defining a reusable component with FXML
     */
    private Parent root;
    /**
     * An instance of the Product class. This field is used to store the
     * object of the current product displaying at this product page
     */
    private Product currentProduct;
    /**
     * A rating that is used to display the product's rating (number of stars)
     */
    @FXML
    private Rating rating;

    /**
     * A label that is used to display the seller's name
     */
    @FXML
    private Label sellerName;

    /**
     * An image view that is used to display the product's image
     */
    @FXML
    private ImageView productImage;

    /**
     * A label that is used to display the product's name
     */
    @FXML
    private Label name;

    /**
     * A label that is used to display the product's category
     */
    @FXML
    private Label category;

    /**
     * A label that is used to display the country of origin
     */
    @FXML
    private Label country;

    /**
     * A label that is used to display the product's price
     */
    @FXML
    private Label priceLabel;

    /**
     * A label that is used to display the product's description
     */
    @FXML
    private Label productDescription;

    /**
     * A label to display the desired quantity to be bought by the user
     */
    @FXML
    private Label quantity;

    /**
     * A label that is used to display where product will be shipped from
     */
    @FXML
    private Label shipFrom;

    /**
     * A label that is used to display the product's stock
     */
    @FXML
    private Label stock;

    /**
     * A profile icon button that could forward the user to the user's profile page
     */
    @FXML
    private Button profileIcon;

    /**
     * A home icon button that could forward the user to the home page
     */
    @FXML
    private Button homeIcon;

    /**
     * An image view that is used to display the add to favorite icon
     */
    @FXML
    private ImageView favorite;

    /**
     * A layout component which positions all its child nodes (components) in a vertical column.
     * It acts as a container to contain the autogenerated comments in the comment section.
     */
    @FXML
    private VBox vBox;

    /**
     * The Chat with seller button
     */
    @FXML
    private Button chatWithSellerBtn;

    /**
     * This method is used to fill product information automatically into product-page.fxml
     *
     * @param product An instance of the Product class
     */
    @FXML
    public void autoFill(Product product) {

        //Save the object of the current product
        this.currentProduct = product;

        //Autofill the product information into product page
        sellerName.setText(product.getSellerName());
        priceLabel.setText(String.valueOf(df.format(product.getProductPrice())));
        category.setText(product.getCategory());
        name.setText(product.getProductName());
        country.setText("Malaysia");
        stock.setText(String.valueOf(product.getNumOfStock()));
        shipFrom.setText(product.getAddress());
        productDescription.setText(product.getDescription());
        rating.setRating(1.0 * ((product.getNumOfFiveStars() * 5) + (product.getNumOfFourStars() * 4) + (product.getNumOfThreeStars() * 3) + (product.getNumOfTwoStars() * 2) + (product.getNumOfOneStars()))
                / (product.getNumOfOneStars() + product.getNumOfTwoStars() + product.getNumOfThreeStars() + product.getNumOfFourStars() + product.getNumOfFiveStars()));
        Image image = new Image(new File("src/main/resources/images/" + product.getProductImagePath() + ".png").toURI().toString());
        productImage.setImage(image);
        displayProductReview(product.getProductImagePath());
    }

    /**
     * This initialize method prevent mouse clicking on the rating node,
     * show tooltip message when user point at the profile/home icon, and
     * plays the fade in animation for the chat with seller button when this
     * page is initialized
     */
    @FXML
    public void initialize() {
        // prevent mouse clicking on the rating node
        rating.setMouseTransparent(true);
        rating.setFocusTraversable(false);

        // Show tooltip message when user point at the icon
        final Tooltip tooltipProfile = new Tooltip();
        tooltipProfile.setText("My Profile");
        profileIcon.setTooltip(tooltipProfile);
        profileIcon.getTooltip().setOnShowing(p -> {
            Bounds bProfile = profileIcon.localToScreen(profileIcon.getBoundsInLocal());
            profileIcon.getTooltip().setX(bProfile.getMaxX() - 70);
            profileIcon.getTooltip().setY(bProfile.getMinY() + 35);
        });

        final Tooltip tooltipHome = new Tooltip();
        tooltipHome.setText("Homepage");
        homeIcon.setTooltip(tooltipHome);
        homeIcon.getTooltip().setOnShowing(h -> {
            Bounds bHome = homeIcon.localToScreen(homeIcon.getBoundsInLocal());
            homeIcon.getTooltip().setX(bHome.getMaxX() - 60);
            homeIcon.getTooltip().setY(bHome.getMinY() + 35);
        });

        // Fade in chat with seller button
        FadeTransition fadeInChatWithSellerBtn = new FadeTransition(Duration.seconds(1.3), chatWithSellerBtn);
        fadeInChatWithSellerBtn.setFromValue(0);
        fadeInChatWithSellerBtn.setToValue(1);
        fadeInChatWithSellerBtn.play();
    }

    /**
     * This method will direct user to user homepage after clicking it
     */
    @FXML
    void homeButtonPressed(MouseEvent event) throws IOException {
        // Forward user to home page
        root = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("home-page.fxml")));
        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        scene = new Scene(root);
        scene.getStylesheets().add(Objects.requireNonNull(getClass().getResource("styling.css")).toExternalForm());
        stage.setScene(scene);
        stage.show();
    }

    /**
     * This method will direct user to user profile page after clicking it
     *
     * @param event An instance of the MouseEvent class
     * @throws IOException when the files are not found
     */
    @FXML
    void userProfileButtonPressed(MouseEvent event) throws IOException {
        // prevent autofocus to the text field
        Platform.runLater(() -> root.requestFocus());

        // Forward user to user profile page
        root = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("user-profile-page.fxml")));
        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        scene = new Scene(root);
        scene.getStylesheets().add(Objects.requireNonNull(getClass().getResource("styling.css")).toExternalForm());
        stage.setScene(scene);
        stage.show();
    }

    /**
     * This method will add the cart item to the cart.json file when it is pressed, and
     * inform the user that the item is added to cart successfully.
     */
    @FXML
    void addToCartButtonPressed() {
        JsonFileUtil jsonFileUtil = new JsonFileUtil();
        jsonFileUtil.writeCartFile(currentProduct, Integer.parseInt(quantity.getText()));

        // inform the user that the item is added to cart successfully
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("Successful");
        alert.setHeaderText(null);
        alert.setContentText("Item added to cart successfully.");
        alert.showAndWait();

    }

    /**
     * This method decreases the quantity in the quantity label when it is pressed and the quantity currently is greater than one
     */
    @FXML
    void decreaseQuantityButtonPressed() {
        int currentQuantity = Integer.parseInt(quantity.getText());
        if (currentQuantity > 1) {
            quantity.setText(Integer.toString(currentQuantity - 1));
        }
    }

    /**
     * This method increases the quantity in the quantity label when it is pressed
     */
    @FXML
    void increaseQuantityButtonPressed() {
        int currentQuantity = Integer.parseInt(quantity.getText());
        quantity.setText(Integer.toString(currentQuantity + 1));
    }

    /**
     * This method will add the product to favorite.json file when it is pressed, and
     * change the image to filled love shape to indicate that the item is added to their favorite list
     */
    @FXML
    void favoriteButtonPressed() {
        JsonFileUtil jsonFileUtil = new JsonFileUtil();
        jsonFileUtil.writeFavoriteFile(currentProduct);
        URL icon = this.getClass().getResource("/images/favoriteButtonPressed.png");
        Image image = new Image(String.valueOf(icon));
        favorite.setImage(image);
    }

    /**
     * This method will allow the user to buy the products when it is pressed after some validation,
     * request the payment password from the user, write the item in the orders.json file,
     * send notification email to the seller involves and connect to database to subtract the
     * amount required from the user's balance and increases the product's sales in the database
     */
    @FXML
    void BuyNowButtonPressed() {
        // calculate the total price in 2 decimal places
        double totalPrice = (int) (Integer.parseInt(quantity.getText()) * Double.parseDouble(priceLabel.getText()) * 100 + 0.5) / 100.0;

        // check whether the user have set their payment password before
        if (User.getPaymentPassword() == null) {
            // if the user haven't set the payment password before, ask them to set it first
            Alert alert = new Alert(Alert.AlertType.INFORMATION);
            alert.setTitle("A Payment Password is Required");
            alert.setHeaderText(null);
            alert.setContentText("Please set your payment password at the profile page.");
            alert.showAndWait();

        } else if (Integer.parseInt(quantity.getText()) > currentProduct.getNumOfStock()) {
            // if the stock is not enough
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Insufficient stock");
            alert.setHeaderText(null);
            alert.setContentText("The number of stocks for this product is insufficient. Please wait until the seller increases their stock.");
            alert.showAndWait();

        } else if (User.getBalance() < totalPrice) {
            // if the user does not have enough balance, ask them to top up
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Payment Unsuccessful");
            alert.setHeaderText(null);
            alert.setContentText("You do not have sufficient balance to proceed with this payment.");
            alert.showAndWait();

        } else {
            // if the user do have enough balance
            // request payment password
            // request for payment password to proceed using a custom dialog box
            Dialog<String> dialog = new Dialog<>();
            dialog.setTitle("Processing Payment...");
            dialog.setHeaderText(String.format("The total amount of payment is RM%.2f\nPlease key-in your " +
                    "payment password to proceed with the payment.", Integer.parseInt(quantity.getText()) * Double.parseDouble(priceLabel.getText())));
            dialog.getDialogPane().getButtonTypes().addAll(ButtonType.OK, ButtonType.CANCEL);

            PasswordField passwordField = new PasswordField();

            GridPane grid = new GridPane();
            grid.setVgap(10);
            grid.setHgap(10);
            grid.setPadding(new Insets(20, 150, 10, 10));
            grid.add(new Label("Enter payment password: "), 0, 0);
            grid.add(passwordField, 1, 0);
            dialog.getDialogPane().setContent(grid);

            Platform.runLater(passwordField::requestFocus);

            Optional<String> result = dialog.showAndWait();

            if (result.isPresent() && passwordField.getText().equals(User.getPaymentPassword())) {
                // if payment password entered is correct
                // subtract the amount from the user's balance in the User class
                double balance = User.getBalance() - totalPrice;
                User.setBalance(balance);

                // connect to the database to update the new balance, increment the product's number of sales, and decrease the number of stock
                Connection connection = null;
                PreparedStatement psUpdate = null;
                PreparedStatement psIncrementSales = null;
                PreparedStatement psDecrementStocks = null;

                try {
                    DatabaseConnection db = new DatabaseConnection();
                    connection = db.getConnection();

                    psUpdate = connection.prepareStatement("UPDATE user_account SET balance = ? WHERE email = ?");
                    psUpdate.setString(1, String.format("%.2f", balance));
                    psUpdate.setString(2, User.getEmail());
                    psUpdate.executeUpdate();

                    psIncrementSales = connection.prepareStatement("UPDATE product_info SET numberOfSales = ? WHERE sellerEmail = ? AND name = ?");
                    psIncrementSales.setString(1, Integer.toString(currentProduct.getNumberOfSales() + (Integer.parseInt(quantity.getText()))));
                    psIncrementSales.setString(2, currentProduct.getSellerEmail());
                    psIncrementSales.setString(3, currentProduct.getProductName());
                    psIncrementSales.executeUpdate();

                    psDecrementStocks = connection.prepareStatement("UPDATE product_info SET numOfStock = ? WHERE sellerEmail = ? AND name = ?");
                    psDecrementStocks.setString(1, Integer.toString(currentProduct.getNumOfStock() - (Integer.parseInt(quantity.getText()))));
                    psDecrementStocks.setString(2, currentProduct.getSellerEmail());
                    psDecrementStocks.setString(3, currentProduct.getProductName());
                    psDecrementStocks.executeUpdate();

                } catch (SQLException e) {
                    e.printStackTrace();

                } finally {
                    if (psDecrementStocks != null) {
                        try {
                            psDecrementStocks.close();
                        } catch (SQLException e) {
                            e.printStackTrace();
                        }
                    }
                    if (psUpdate != null) {
                        try {
                            psUpdate.close();
                        } catch (SQLException e) {
                            e.printStackTrace();
                        }
                    }
                    if (psIncrementSales != null) {
                        try {
                            psIncrementSales.close();
                        } catch (SQLException e) {
                            e.printStackTrace();
                        }
                    }
                    if (connection != null) {
                        try {
                            connection.close();
                        } catch (SQLException e) {
                            e.printStackTrace();
                        }
                    }
                }

                // add ordered item into orders.json file
                JsonFileUtil jsonFileUtil = new JsonFileUtil();
                jsonFileUtil.writeOrdersFile(currentProduct, Integer.parseInt(quantity.getText()));

                try {
                    // send notification email to the seller
                    Email.sendNotification(currentProduct.getSellerEmail(), currentProduct.getProductName(), Integer.parseInt(quantity.getText()), currentProduct.getProductPrice());

                } catch (MessagingException e) {
                    e.printStackTrace();
                }

                // inform the user that the payment is successful
                Alert alert = new Alert(Alert.AlertType.INFORMATION);
                alert.setTitle("Payment successful");
                alert.setHeaderText(null);
                alert.setContentText("The payment is successful. You can view your orders at Profile > My Purchase > Orders.");
                alert.showAndWait();
            } else {
                // if the payment password is incorrect
                Alert alert = new Alert(Alert.AlertType.ERROR);
                alert.setTitle("Payment Unsuccessful");
                alert.setHeaderText(null);
                alert.setContentText("The payment password entered is incorrect.");
                alert.showAndWait();

            }
        }
    }

    /**
     * Pop-up a chat with seller window after it is pressed
     *
     * @throws IOException when the file is not found
     */
    @FXML
    void chatWithSellerBtnPressed() throws IOException {
        // pop up the chat with seller page
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("chat-with-seller-page.fxml"));
        Parent root = fxmlLoader.load();
        ChatWithSellerController chatWithSellerController = fxmlLoader.getController();
        chatWithSellerController.setInfo(currentProduct.getSellerName(), currentProduct.getSellerEmail(), currentProduct.getProductName());
        Stage stage = new Stage();
        stage.initStyle(StageStyle.DECORATED);
        stage.setTitle("Chat With Seller");
        stage.setScene(new Scene(root));
        stage.setResizable(false);
        stage.initModality(Modality.APPLICATION_MODAL);
        stage.showAndWait();
    }

    /**
     * This method is used to display the product's review
     */
    void displayProductReview(String imageName) {
        // clear the previous contents in the vbox
        vBox.getChildren().clear();

        JsonFileUtil jsonFileUtil = new JsonFileUtil();
        // create an array list and call the product review list method
        List<ProductReview> productReviewList = new ArrayList<>(jsonFileUtil.readProductReviewFile(imageName));
        // loop through the productReviewList, fills in the product review, username, seller reply and add it to the vbox
        for (ProductReview productReview : productReviewList) {
            try {
                FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("review-template.fxml"));
                AnchorPane anchorPane = fxmlLoader.load();
                ReviewController reviewController = fxmlLoader.getController();
                reviewController.setData(productReview);
                vBox.getChildren().add(anchorPane);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
