package com.example.omazonproject;

import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Bounds;
import javafx.geometry.Insets;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Region;
import javafx.stage.Stage;
import org.controlsfx.control.textfield.AutoCompletionBinding;
import org.controlsfx.control.textfield.TextFields;
import org.w3c.dom.events.EventException;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicReference;


/**
 * This class acts as a controller for the homepage
 *
 * @author XiangLun
 */
public class HomepageController {

    /**
     * Stage is used to represent a window in a JavaFX desktop application
     */
    private Stage stage;

    /**
     * Scene is the container for all content in a scene graph
     */
    private Scene scene;

    /**
     * Root provides a solution to the issue of defining a reusable component with FXML
     */
    private Parent root;

    /**
     * The profile icon button
     */
    @FXML
    private Button profileIcon;

    /**
     * The home icon button
     */
    @FXML
    private Button homeIcon;

    /**
     * The log-out icon button
     */
    @FXML
    private Button logOutIcon;

    /**
     * A combo box to store product's category
     */
    @FXML
    private ComboBox<String> productCategory_home;

    /**
     * A text field for the user to enter the product they want to search for
     */
    @FXML
    private TextField searchItems;

    /**
     * A layout component which lays out its child components in a grid.
     * It acts as a container to contain all the autogenerated products.
     */
    @FXML
    private GridPane gridPane;

    /**
     * An image view to display top 1 best-selling product
     */
    @FXML
    private ImageView top1;

    /**
     * An image view to display top 2 best-selling product
     */
    @FXML
    private ImageView top2;

    /**
     * An image view to display top 3 best-selling product
     */
    @FXML
    private ImageView top3;

    /**
     * An array list to store product objects (to get all products from database and display at user homepage)
     */
    public List<Product> products = new ArrayList<>();

    /**
     * An object of the ProductListener class
     */
    public ProductListener productListener;

    /**
     * An array to get three best-selling product indexes
     */
    public int[] getMaxIndex = new int[3];

    /**
     * An array list to store product name and seller name so that it can be used for autocomplete search
     */
    ArrayList<String> productName = new ArrayList<>();

    /**
     * An array list to store product objects (to get top3 best-selling product)
     */
    List<Product> objects = new ArrayList<>();

    @FXML
    public void initialize() throws Exception {

        productCategory_home.getItems().addAll("Electronic Devices", "Fashion", "Food", "Health & Beauty", "Sports", "TV & Home Appliances");
        productCategory_home.setPromptText("Select");

        //Autocomplete search
        //If the product category is not selected, view all the product in database
        getProductNameFromDatabase("Select");
        getSellerNameFromDatabase();
        AtomicReference<AutoCompletionBinding> acb = new AtomicReference<>(TextFields.bindAutoCompletion(searchItems, productName));

        //Select product category
        productCategory_home.setOnAction(event -> {
            try {
                String get = productCategory_home.getSelectionModel().getSelectedItem();
                if (get != null) {
                    acb.get().dispose();
                    productName.clear();
                    getProductNameFromDatabase(get);
                    acb.set(TextFields.bindAutoCompletion(searchItems, productName));
                }
            } catch (EventException e) {
                e.printStackTrace();
            }
        });

        // Show tooltip message when user point at the icon
        final Tooltip tooltipProfile = new Tooltip();
        tooltipProfile.setText("My Profile");
        profileIcon.setTooltip(tooltipProfile);
        profileIcon.getTooltip().setOnShowing(p -> {
            Bounds bProfile = profileIcon.localToScreen(profileIcon.getBoundsInLocal());
            profileIcon.getTooltip().setX(bProfile.getMaxX() - 70);
            profileIcon.getTooltip().setY(bProfile.getMinY() + 35);
        });

        final Tooltip tooltipHome = new Tooltip();
        tooltipHome.setText("Homepage");
        homeIcon.setTooltip(tooltipHome);
        homeIcon.getTooltip().setOnShowing(h -> {
            Bounds bHome = homeIcon.localToScreen(homeIcon.getBoundsInLocal());
            homeIcon.getTooltip().setX(bHome.getMaxX() - 60);
            homeIcon.getTooltip().setY(bHome.getMinY() + 35);
        });

        final Tooltip tooltipLogOut = new Tooltip();
        tooltipLogOut.setText("Log Out");
        logOutIcon.setTooltip(tooltipLogOut);
        logOutIcon.getTooltip().setOnShowing(l -> {
            Bounds bLog = logOutIcon.localToScreen(logOutIcon.getBoundsInLocal());
            logOutIcon.getTooltip().setX(bLog.getMaxX() - 40);
            logOutIcon.getTooltip().setY(bLog.getMinY() + 35);
        });


        //Create a list to store all product objects
        Connection connectDB = null;
        Statement statement = null;
        ResultSet bestSellingProductResult = null;

        int count = 0;

        try {

            DatabaseConnection connectNow = new DatabaseConnection();
            connectDB = connectNow.getConnection();
            statement = connectDB.createStatement();
            bestSellingProductResult = statement.executeQuery("SELECT * FROM product_info ");

            while (bestSellingProductResult.next()) {
                objects.add(count, new Product());
                objects.get(count).setSellerName(bestSellingProductResult.getString("sellerName"));
                objects.get(count).setSellerEmail(bestSellingProductResult.getString("sellerEmail"));
                objects.get(count).setProductName(bestSellingProductResult.getString("name"));
                objects.get(count).setProductPrice(bestSellingProductResult.getDouble("price"));
                objects.get(count).setCategory(bestSellingProductResult.getString("category"));
                objects.get(count).setDescription(bestSellingProductResult.getString("description"));
                objects.get(count).setNumOfOneStars(bestSellingProductResult.getInt("numOfOneStars"));
                objects.get(count).setNumOfTwoStars(bestSellingProductResult.getInt("numOfTwoStars"));
                objects.get(count).setNumOfThreeStars(bestSellingProductResult.getInt("numOfThreeStars"));
                objects.get(count).setNumOfFourStars(bestSellingProductResult.getInt("numOfFourStars"));
                objects.get(count).setNumOfFiveStars(bestSellingProductResult.getInt("numOfFiveStars"));
                objects.get(count).setNumberOfSales((bestSellingProductResult.getInt("numberOfSales")));
                objects.get(count).setProductImagePath(bestSellingProductResult.getString("imageName"));
                objects.get(count).setProductStock(bestSellingProductResult.getInt("numOfStock"));
                objects.get(count).setAddress(bestSellingProductResult.getString("sellerAddress"));
                count = count + 1;
            }


        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (bestSellingProductResult != null) {
                try {
                    bestSellingProductResult.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (connectDB != null) {
                try {
                    connectDB.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }

        //Get top 3 best-selling products by checking the number of sales for each product
        ArrayList<Integer> index = new ArrayList<>();

        int max;
        int maxIndex = 0;

        for (int i = 0; i < 3; i++) {
            max = 0;
            for (int j = 0; j < count; j++) {
                if (!index.contains(j)) {
                    if (objects.get(j).getNumberOfSales() >= max) {
                        maxIndex = j;
                        max = objects.get(j).getNumberOfSales();
                    }
                }
            }
            index.add(maxIndex);
            getMaxIndex[i] = maxIndex;
        }

        //Get the top 3 best-selling product images from images folder
        String Top1 = objects.get(getMaxIndex[0]).getProductImagePath();
        String Top2 = objects.get(getMaxIndex[1]).getProductImagePath();
        String Top3 = objects.get(getMaxIndex[2]).getProductImagePath();

        //Display the top 3 best-selling product images at home page
        Image image1 = new Image(new File("src/main/resources/images/" + Top1 + ".png").toURI().toString());
        Image image2 = new Image(new File("src/main/resources/images/" + Top2 + ".png").toURI().toString());
        Image image3 = new Image(new File("src/main/resources/images/" + Top3 + ".png").toURI().toString());
        top1.setImage(image1);
        top2.setImage(image2);
        top3.setImage(image3);


        // display all the products at user homepage
        // add all products in products list
        getProduct();

        productListener = new ProductListener() {
            @Override
            public void onClickListener(Product product) throws IOException {
                changeScene(product);
            }
        };

        int column = 0;
        int row = 1;

        try {

            for (Product product : products) {

                FXMLLoader loader = new FXMLLoader();
                loader.setLocation(getClass().getResource("product-template.fxml"));
                AnchorPane anchorPane = loader.load();

                ProductController productController = loader.getController();
                // set product name, product price and product image
                // display it at seller product page
                productController.setData(product, productListener);


                if (column == 4) {
                    column = 0;
                    row++;
                }

                gridPane.add(anchorPane, column++, row);

                //set grid width
                gridPane.setMinWidth(Region.USE_COMPUTED_SIZE);
                gridPane.setPrefWidth(Region.USE_COMPUTED_SIZE);

                //set grid height
                gridPane.setMinHeight(Region.USE_COMPUTED_SIZE);
                gridPane.setPrefHeight(Region.USE_COMPUTED_SIZE);
                gridPane.setMaxHeight(Region.USE_PREF_SIZE);

                GridPane.setMargin(anchorPane, new Insets(28));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is used to get all products from database and display it at user homepage
     */
    private void getProduct() {

        Connection connectDB = null;
        Statement statement = null;
        ResultSet Result = null;

        try {
            DatabaseConnection connectNow = new DatabaseConnection();
            connectDB = connectNow.getConnection();
            statement = connectDB.createStatement();

            Result = statement.executeQuery("SELECT * FROM product_info");

            int count = 0;
            while (Result.next()) {
                // add all product information into products list
                products.add(count, new Product());
                products.get(count).setSellerName(Result.getString("sellerName"));
                products.get(count).setSellerEmail(Result.getString("sellerEmail"));
                products.get(count).setProductName(Result.getString("name"));
                products.get(count).setProductPrice(Result.getDouble("price"));
                products.get(count).setCategory(Result.getString("category"));
                products.get(count).setDescription(Result.getString("description"));
                products.get(count).setNumOfOneStars(Result.getInt("numOfOneStars"));
                products.get(count).setNumOfTwoStars(Result.getInt("numOfTwoStars"));
                products.get(count).setNumOfThreeStars(Result.getInt("numOfThreeStars"));
                products.get(count).setNumOfFourStars(Result.getInt("numOfFourStars"));
                products.get(count).setNumOfFiveStars(Result.getInt("numOfFiveStars"));
                products.get(count).setNumberOfSales((Result.getInt("numberOfSales")));
                products.get(count).setProductImagePath(Result.getString("imageName"));
                products.get(count).setProductStock(Result.getInt("numOfStock"));
                products.get(count).setAddress(Result.getString("sellerAddress"));
                count++;
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (Result != null) {
                try {
                    Result.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (connectDB != null) {
                try {
                    connectDB.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    /**
     * This method will direct user to top 1 best-selling product page
     *
     * @param event An instance of the ActionEvent class
     * @throws IOException when the resource file is not found
     */
    @FXML
    void top1Pressed(ActionEvent event) throws IOException {
        //Forward user to product page based on product information
        FXMLLoader loader = new FXMLLoader(getClass().getResource("product-page.fxml"));
        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        stage.setScene(new Scene(loader.load()));
        AutoFillProductPageClass controller = loader.getController();
        stage.show();
        controller.autoFill(objects.get(getMaxIndex[0]));
    }

    /**
     * This method will direct user to top 2 best-selling product page
     *
     * @param event An instance of the ActionEvent class
     * @throws IOException when the resource file is not found
     */
    @FXML
    void top2Pressed(ActionEvent event) throws IOException {
        //Forward user to product page based on product information
        FXMLLoader loader = new FXMLLoader(getClass().getResource("product-page.fxml"));
        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        stage.setScene(new Scene(loader.load()));
        AutoFillProductPageClass controller = loader.getController();
        stage.show();
        controller.autoFill(objects.get(getMaxIndex[1]));
    }

    /**
     * This method will direct user to top 3 best-selling product page
     *
     * @param event An instance of the ActionEvent class
     * @throws IOException when the resource file is not found
     */
    @FXML
    void top3Pressed(ActionEvent event) throws IOException {
        //Forward user to product page based on product information
        FXMLLoader loader = new FXMLLoader(getClass().getResource("product-page.fxml"));
        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        stage.setScene(new Scene(loader.load()));
        AutoFillProductPageClass controller = loader.getController();
        stage.show();
        controller.autoFill(objects.get(getMaxIndex[2]));
    }

    /**
     * This method is used to log out
     * This method will direct user to user login page after clicking it
     *
     * @param event An instance of the ActionEvent class
     * @throws IOException when the resource file is ot found
     */
    @FXML
    void logOutButtonPressed(ActionEvent event) throws IOException {
        // forward user to the login page
        root = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("main-login-page.fxml")));
        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        scene = new Scene(root);
        scene.getStylesheets().add(Objects.requireNonNull(getClass().getResource("styling.css")).toExternalForm());
        stage.setScene(scene);
        stage.show();
    }

    /**
     * This method will direct user to the profile page after clicking it
     *
     * @param event An instance of the ActionEvent class
     * @throws IOException when the resource file is not found
     */
    @FXML
    void profileButtonPressed(ActionEvent event) throws IOException {
        // create an instance of the FXMLLoader class
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("user-profile-page.fxml"));
        root = fxmlLoader.load();

        // prevent autofocus to the text field
        Platform.runLater(() -> root.requestFocus());

        // display the scene
        root = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("user-profile-page.fxml")));
        stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        scene = new Scene(root);
        stage.setScene(scene);
        stage.show();
    }

    /**
     * This method will direct user to product search page based on the product name entered by the user at search bar
     *
     * @param event An instance of the ActionEvent class
     * @throws IOException when the resource file is not found
     */
    @FXML
    void searchButtonPressed(ActionEvent event) throws IOException {

        String productToSearchName = searchItems.getText();

        if (!searchItems.getText().isBlank()) {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("product-search-page.fxml"));
            root = loader.load();

            ProductSearchController productSearchController = loader.getController();
            productSearchController.initialize(productToSearchName);

            stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
            scene = new Scene(root);
            stage.setScene(scene);
            stage.show();

        } else {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Enter something to search");
            alert.setHeaderText(null);
            alert.setContentText("Please enter something to search");
            alert.showAndWait();
        }


    }

    /**
     * This method is used to get product names from database and store it in an array list named productName
     * Therefore it can be used by autocomplete search
     */
    void getProductNameFromDatabase(String PRODUCTCATEGORY) {

        Connection connectDB = null;
        Statement statement = null;
        ResultSet Result = null;

        try {
            DatabaseConnection connectNow = new DatabaseConnection();
            connectDB = connectNow.getConnection();
            statement = connectDB.createStatement();

            if (PRODUCTCATEGORY.equals("Select")) {
                Result = statement.executeQuery("SELECT * FROM product_info");
            } else {
                Result = statement.executeQuery("SELECT * FROM product_info where category = '" + PRODUCTCATEGORY + "'");
            }

            while (Result.next()) {
                String PRODUCTNAME = Result.getString("name");
                productName.add(PRODUCTNAME);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (Result != null) {
                try {
                    Result.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (connectDB != null) {
                try {
                    connectDB.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    /**
     * This method is used get seller names from database and store it in an array list named productName
     * Therefore it can be used by autocomplete search
     */
    void getSellerNameFromDatabase() {

        Connection connectDB = null;
        Statement statement = null;
        ResultSet sellerResult = null;

        try {
            DatabaseConnection connectNow = new DatabaseConnection();
            connectDB = connectNow.getConnection();
            statement = connectDB.createStatement();

            sellerResult = statement.executeQuery("SELECT * FROM seller_account");

            while (sellerResult.next()) {
                String SELLERNAME = sellerResult.getString("sellerName");
                productName.add(SELLERNAME);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (sellerResult != null) {
                try {
                    sellerResult.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (connectDB != null) {
                try {
                    connectDB.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    /**
     * This method will direct user to product page and automatically fill product information into product page
     * This method will be called when user click the product at user home page
     *
     * @param product An instance of the Product class
     * @throws IOException when the resource file is not found
     */
    private void changeScene(Product product) throws IOException {
        FXMLLoader loader = new FXMLLoader(getClass().getResource("product-page.fxml"));
        ProductController productController = new ProductController();

        stage = (Stage) ((Node) productController.event.getSource()).getScene().getWindow();
        stage.setScene(new Scene(loader.load()));
        AutoFillProductPageClass controller = loader.getController();
        stage.show();
        controller.autoFill(product);
    }

}